name: colab-construct

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  construct:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache conda
        uses: actions/cache@v2
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{hashFiles('environment.yml') }}

      - uses: conda-incubator/setup-miniconda@v2
        name: Install dependencies
        with:
          environment-file: colab/constructor-env.yml
          activate-environment: constructor
          auto-activate-base: false
          miniforge-version: latest
          miniforge-variant: Mambaforge
          use-mamba: true

      - name: Describe environment
        run: |
          pwd
          ls
          conda list

      - name: Construct installer
        run: |
          constructor --platform linux-64 colab

      - name: Add installer to release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: condacolab-constructor
          files: |
            ./openmm-condacolab-*.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}